# Generated by Django 5.2.8 on 2025-12-02 16:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import payouts.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("code", models.CharField(help_text="Код в формате ISO 4217", max_length=3, unique=True, verbose_name="Код")),
            ],
            options={
                "verbose_name": "Валюта",
                "verbose_name_plural": "Валюты",
            },
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("pending", "Ожидает обработки"), ("processing", "В обработке"), ("approved", "Одобрена"), ("rejected", "Отклонена"), ("paid", "Выплачена"), ("canceled", "Отменена")], db_index=True, default="pending", max_length=20, verbose_name="Статус заявки")),
                ("payment", models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100000000.0)], verbose_name="Сумма выплаты")),
                ("description", models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name="Описание")),
                ("bik", models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9), payouts.validators.validate_digits], verbose_name="БИК банка получателя")),
                ("correspondent_account", models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(20), payouts.validators.validate_digits], verbose_name="Корреспондентский счёт получателя")),
                ("bank_account_number", models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(20), payouts.validators.validate_digits], verbose_name="Номер банковского счёта получателя")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("currency", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="payouts.currency", verbose_name="Валюта")),
            ],
            options={
                "verbose_name": "Заявка на выплату денежных средств",
                "verbose_name_plural": "Заявки на выплату денежных средств",
                "ordering": ("-created_at",),
            },
        ),
    ]
